name:  Print Hello World
on:
  push:
jobs:
  print:
    runs-on:  ubuntu-latest
    steps:
      - name: Print Hello World
        run:  echo "Hello World"
      - name: Repo Clone
        uses: actions/checkout@v4
      - name: Setup Node version
        uses: actions/setup-node@4
        with:
          node-version: 18.x
      - name: Add numbers
        run: node hello.js

    
  
